version: '3.7'

services:
    db:
        image: mongo:latest
        container_name: db
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin
            MONGO_INITDB_DATABASE: db1
        ports:
          - 27017:27017
    transacao:
        container_name: transacao
        build:
          context: ./
          dockerfile: transacao/Dockerfile
        restart: always
        depends_on:
          - db
        links:
          - db
        ports:
          - 3002:3002
    users:
        container_name: users
        build:
          context: ./
          dockerfile: users/Dockerfile
        restart: always
        depends_on:
          - db
        links:
          - db
        ports:
          - 3001:3001
    gateway:
        container_name: gateway
        build:
          context: ./
          dockerfile: gateway/Dockerfile
        depends_on: 
          - users
          - transacao
        links:
          - users
          - transacao
        restart: always
        ports:
          - 3000:3000
